export { default as ImageSlider } from './ImageSlider'
export { default as SliceZone} from './SliceZone'
export { default as CustomSolution } from './CustomSolution'
export { default as Offering } from './Offering'
export { default as OurService } from './OurService'
export { default as CustomMadeBlock } from './CustomMadeBlock'
export { default as BackgroundImageSlice } from './BackgroundImageSlice'
export { default as UpcomingEvents } from './UpcomingEvents'
export { default as VideoBlock} from './VideoBlock'
export { default as ImageGallery } from './ImageGallery'
export { default as RegisterModal } from './RegisterModal'